import { useState, useEffect } from 'react';
import { ArrowLeft, Calendar, MapPin, AlertTriangle, Clock, Navigation, CheckCircle2, Bell, Plus, RefreshCw } from 'lucide-react';
import { Card } from '@/app/components/ui/card';
import { Button } from '@/app/components/ui/button';
import { Badge } from '@/app/components/ui/badge';
import { GoogleCalendarEventForm, EventFormData } from '@/app/components/GoogleCalendarEventForm';
import {
  fetchCompanyEvents,
  createScheduledEvent,
  markEventCompleted,
  ScheduledEvent,
  EventType,
} from '@/app/services/calendarEventsService';
import { isSupabaseConfigured } from '@/app/services/supabase';
import { toast } from 'sonner';

interface CalendarViewProps {
  onBack: () => void;
  onViewRouteOptimizer: () => void;
  companyId?: string;
  companyName?: string;
  branchId?: string;
}

interface DisplayEvent {
  id: string;
  date: string;
  title: string;
  type: EventType;
  priority: 'critical' | 'high' | 'medium' | 'low';
  location: string;
  time: string;
  deadline: string | null;
  status: string;
  autoGenerated: boolean;
  company?: string;
  notes?: string;
  frequency?: string;
  lastCompleted?: string;
  source?: ScheduledEvent;
}

// Estructura de inspecciones recurrentes (autoalimentadas)
interface RecurringInspection {
  id: string;
  originalInspectionId: string;
  name: string;
  type: 'activos' | 'instalaciones' | 'epp' | 'documentos';
  frequency: 'mensual' | 'trimestral' | 'semestral' | 'anual';
  lastCompletedDate: string;
  nextDueDate: string;
  location: string;
  company: string;
  notes?: string;
  autoGenerated: boolean;
}

// Base de inspecciones recurrentes autoalimentadas
const recurringInspections: RecurringInspection[] = [
  {
    id: 'REC-001',
    originalInspectionId: 'INS-2025-12-15',
    name: 'Inspección de Extintores - Sector A',
    type: 'activos',
    frequency: 'mensual',
    lastCompletedDate: '2025-12-15',
    nextDueDate: '2026-01-15',
    location: 'Sucursal Maipú - Sector Producción A',
    company: 'Constructora Los Andes S.A.',
    notes: 'Verificar presión y accesibilidad',
    autoGenerated: true
  },
  {
    id: 'REC-002',
    originalInspectionId: 'INS-2025-10-20',
    name: 'Inspección Trimestral Matriz IPER',
    type: 'documentos',
    frequency: 'trimestral',
    lastCompletedDate: '2025-10-20',
    nextDueDate: '2026-01-20',
    location: 'Sucursal La Serena',
    company: 'Minera del Norte',
    notes: 'Actualización según DS 132',
    autoGenerated: true
  },
  {
    id: 'REC-003',
    originalInspectionId: 'INS-2025-11-30',
    name: 'Inspección de Arneses y EPP Altura',
    type: 'epp',
    frequency: 'semestral',
    lastCompletedDate: '2025-07-30',
    nextDueDate: '2026-01-30',
    location: 'Obra Piso 12 - Puente Alto',
    company: 'Constructora Los Andes S.A.',
    notes: 'Certificación de equipos de altura',
    autoGenerated: true
  },
  {
    id: 'REC-004',
    originalInspectionId: 'INS-2025-09-10',
    name: 'Revisión de Botiquines',
    type: 'instalaciones',
    frequency: 'mensual',
    lastCompletedDate: '2025-12-10',
    nextDueDate: '2026-01-10',
    location: 'Sucursal Centro - Todos los pisos',
    company: 'Transportes Veloz',
    notes: 'Revisar stock y fechas de vencimiento',
    autoGenerated: true
  },
  {
    id: 'REC-005',
    originalInspectionId: 'INS-2025-03-15',
    name: 'Inspección Anual de Escaleras',
    type: 'activos',
    frequency: 'anual',
    lastCompletedDate: '2025-03-15',
    nextDueDate: '2026-03-15',
    location: 'Bodega Central',
    company: 'Constructora Los Andes S.A.',
    notes: 'Revisión estructural completa',
    autoGenerated: true
  },
  {
    id: 'REC-006',
    originalInspectionId: 'INS-2025-12-20',
    name: 'Inspección de Andamios - Proyecto Norte',
    type: 'instalaciones',
    frequency: 'mensual',
    lastCompletedDate: '2025-12-20',
    nextDueDate: '2026-01-20',
    location: 'Obra Norte - Zona Construcción',
    company: 'Constructora Los Andes S.A.',
    notes: 'Revisar estabilidad y señalización',
    autoGenerated: true
  },
  {
    id: 'REC-007',
    originalInspectionId: 'INS-2025-10-05',
    name: 'Inspección Trimestral Instalaciones Eléctricas',
    type: 'instalaciones',
    frequency: 'trimestral',
    lastCompletedDate: '2025-10-05',
    nextDueDate: '2026-01-05',
    location: 'Planta de Producción',
    company: 'Minera del Norte',
    notes: 'Según normativa SEC',
    autoGenerated: true
  }
];

// Función para generar eventos del calendario desde inspecciones recurrentes
const generateCalendarEventsFromInspections = (): any[] => {
  const currentDate = new Date();
  const currentYear = currentDate.getFullYear();
  const currentMonth = currentDate.getMonth();
  
  return recurringInspections
    .filter(inspection => {
      const dueDate = new Date(inspection.nextDueDate);
      // Mostrar solo las del mes actual y próximos 2 meses
      return dueDate.getFullYear() === currentYear && 
             dueDate.getMonth() >= currentMonth && 
             dueDate.getMonth() <= currentMonth + 2;
    })
    .map(inspection => {
      const dueDate = new Date(inspection.nextDueDate);
      const today = new Date();
      const daysUntil = Math.ceil((dueDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
      
      let priority: 'critical' | 'high' | 'medium' = 'medium';
      if (daysUntil <= 3) priority = 'critical';
      else if (daysUntil <= 7) priority = 'high';
      
      return {
        id: `auto-${inspection.id}`,
        date: inspection.nextDueDate,
        title: `${inspection.name} [AUTO]`,
        type: 'inspection',
        priority: priority,
        location: inspection.location,
        time: '09:00',
        deadline: inspection.frequency === 'mensual' ? 'Inspección mensual programada' :
                 inspection.frequency === 'trimestral' ? 'Vencimiento trimestral' :
                 inspection.frequency === 'semestral' ? 'Vencimiento semestral' :
                 'Vencimiento anual',
        status: 'pending',
        frequency: inspection.frequency,
        autoGenerated: true,
        company: inspection.company,
        notes: inspection.notes,
        lastCompleted: inspection.lastCompletedDate
      };
    });
};

// Eventos del calendario con vencimientos legales
const MOCK_CALENDAR_EVENTS: DisplayEvent[] = [
  {
    id: 1,
    date: '2026-01-27',
    title: 'Comité Paritario - Constructora Los Andes',
    type: 'legal',
    priority: 'critical',
    location: 'Sucursal Maipú',
    time: '10:00',
    deadline: 'Mañana vence plazo legal (Art. 66 DS54)',
    status: 'pending',
    autoGenerated: false
  },
  {
    id: 2,
    date: '2026-01-28',
    title: 'Actualización Matriz IPER - Minera del Norte',
    type: 'legal',
    priority: 'high',
    location: 'Sucursal La Serena',
    time: '09:00',
    deadline: 'Vencimiento trimestral (DS 132)',
    status: 'pending',
    autoGenerated: false
  },
  {
    id: 3,
    date: '2026-01-27',
    title: 'Charla de Seguridad - Transportes Veloz',
    type: 'routine',
    priority: 'medium',
    location: 'Sucursal Centro',
    time: '14:30',
    deadline: null,
    status: 'scheduled',
    autoGenerated: false
  },
  {
    id: 4,
    date: '2026-01-29',
    title: 'Inspección EPP - Constructora Los Andes',
    type: 'inspection',
    priority: 'medium',
    location: 'Obra Piso 12',
    time: '11:00',
    deadline: null,
    status: 'scheduled',
    autoGenerated: false
  },
  {
    id: 5,
    date: '2026-01-30',
    title: 'Capacitación Trabajo en Altura',
    type: 'training',
    priority: 'high',
    location: 'Sucursal Puente Alto',
    time: '08:30',
    deadline: 'Requisito SUSESO pre-inicio trabajos',
    status: 'scheduled',
    autoGenerated: false
  },
  // Agregar inspecciones autoalimentadas
  ...generateCalendarEventsFromInspections()
];

// Sugerencias inteligentes
const smartSuggestions = [
  {
    id: 1,
    suggestion: 'Optimizar ruta: Visita Maipú y Puente Alto el mismo día',
    savings: '45 min de traslado, 8 km menos',
    type: 'route',
    actionLabel: 'Ver Ruta Optimizada'
  },
  {
    id: 2,
    suggestion: 'Vencimiento próximo: Actualizar Reglamento Interno en 15 días',
    savings: 'Evita multa de hasta 60 UTM',
    type: 'legal',
    actionLabel: 'Programar Ahora'
  },
  {
    id: 3,
    suggestion: 'Agrupar charlas: 3 empresas cerca del Centro disponibles esta semana',
    savings: '2 horas de trabajo concentrado',
    type: 'productivity',
    actionLabel: 'Ver Agrupación'
  }
];

const daysOfWeek = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'];
const monthNames = ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'];

const eventTypeMap: Record<EventFormData['eventType'], EventType> = {
  inspection: 'inspection',
  training: 'training',
  legal: 'legal',
  meeting: 'routine',
  other: 'routine',
};

const toDisplayEvent = (e: ScheduledEvent, companyName?: string): DisplayEvent => ({
  id: e.id,
  date: e.date,
  title: e.isRecurring ? `${e.title} [AUTO]` : e.title,
  type: e.eventType,
  priority: e.priority,
  location: e.location,
  time: e.time,
  deadline: e.deadlineNote || null,
  status: e.status,
  autoGenerated: e.isRecurring,
  company: companyName,
  notes: e.notes,
  frequency: e.recurrenceFrequency,
  lastCompleted: e.lastCompletedDate,
  source: e,
});

export function CalendarView({ onBack, onViewRouteOptimizer, companyId, companyName, branchId }: CalendarViewProps) {
  const [selectedDate, setSelectedDate] = useState<string>('2026-01-27');
  const [currentMonth] = useState(new Date(2026, 0, 1)); // Enero 2026
  const [showEventForm, setShowEventForm] = useState(false);

  const [calendarEvents, setCalendarEvents] = useState<DisplayEvent[]>(MOCK_CALENDAR_EVENTS);
  const [isLoadingEvents, setIsLoadingEvents] = useState(true);

  const canPersist = Boolean(isSupabaseConfigured && companyId);

  useEffect(() => {
    let cancelled = false;
    const loadEvents = async () => {
      setIsLoadingEvents(true);
      if (!canPersist) {
        if (!cancelled) setCalendarEvents(MOCK_CALENDAR_EVENTS);
        if (!cancelled) setIsLoadingEvents(false);
        return;
      }
      try {
        const data = await fetchCompanyEvents(companyId!);
        if (!cancelled) setCalendarEvents(data.map(e => toDisplayEvent(e, companyName)));
      } catch (err: any) {
        console.warn('No se pudo cargar el calendario desde Supabase:', err.message);
        if (!cancelled) setCalendarEvents(MOCK_CALENDAR_EVENTS);
      } finally {
        if (!cancelled) setIsLoadingEvents(false);
      }
    };
    loadEvents();
    return () => { cancelled = true; };
  }, [companyId, companyName, canPersist]);

  const handleCreateEvent = async (eventData: EventFormData) => {
    if (canPersist) {
      try {
        const created = await createScheduledEvent({
          companyId: companyId!,
          branchId,
          title: eventData.title,
          eventType: eventTypeMap[eventData.eventType],
          eventDate: eventData.startDate,
          eventTime: eventData.startTime,
          location: eventData.location,
          priority: 'medium',
          notes: eventData.description,
        });
        setCalendarEvents(prev => [...prev, toDisplayEvent(created, companyName)]);
      } catch (err: any) {
        toast.error('Error al crear el evento', { description: err.message });
        return;
      }
    }

    toast.success('✅ Evento creado', {
      description: `${eventData.title} agregado al calendario`,
      duration: 3000
    });

    setShowEventForm(false);
  };

  const handleMarkCompleted = async (event: DisplayEvent) => {
    if (canPersist && event.source) {
      try {
        const updated = await markEventCompleted(event.source);
        setCalendarEvents(prev => prev.map(e => (e.id === event.id ? toDisplayEvent(updated, companyName) : e)));
      } catch (err: any) {
        toast.error('Error al marcar como completado', { description: err.message });
        return;
      }
    } else {
      setCalendarEvents(prev => prev.map(e => (e.id === event.id ? { ...e, status: 'completed' } : e)));
    }

    toast.success('✅ Actividad marcada como completada', {
      description: event.autoGenerated ? 'Próxima fecha reprogramada automáticamente' : event.title,
    });
  };

  // Generar días del mes
  const getDaysInMonth = () => {
    const year = currentMonth.getFullYear();
    const month = currentMonth.getMonth();
    const firstDay = new Date(year, month, 1).getDay();
    const daysInMonth = new Date(year, month + 1, 0).getDate();
    
    const days = [];
    
    // Días vacíos al inicio
    for (let i = 0; i < firstDay; i++) {
      days.push(null);
    }
    
    // Días del mes
    for (let day = 1; day <= daysInMonth; day++) {
      const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
      const eventsOnDay = calendarEvents.filter(e => e.date === dateStr);
      const hasLegal = eventsOnDay.some(e => e.type === 'legal');
      const hasCritical = eventsOnDay.some(e => e.priority === 'critical');
      
      days.push({
        day,
        dateStr,
        events: eventsOnDay,
        hasLegal,
        hasCritical
      });
    }
    
    return days;
  };

  const selectedEvents = calendarEvents.filter(e => e.date === selectedDate);

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-zinc-900 transition-colors pb-20 lg:pb-6">
      {/* Header */}
      <div className="bg-white dark:bg-zinc-800 border-b border-slate-200 dark:border-zinc-700">
        <div className="max-w-7xl mx-auto px-4 pt-16 pb-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={onBack}
                className="flex items-center gap-2 text-slate-600 dark:text-zinc-400 hover:text-slate-900 dark:hover:text-white transition-colors"
              >
                <ArrowLeft className="w-5 h-5" />
                <span>Volver</span>
              </button>
              <div>
                <h1 className="text-slate-900 dark:text-white text-xl lg:text-2xl">Itinerario Inteligente</h1>
                <p className="text-sm text-slate-600 dark:text-zinc-400">El "Waze" de la Prevención de Riesgos</p>
              </div>
            </div>
            <Button 
              onClick={onViewRouteOptimizer}
              className="bg-[#003366] hover:bg-[#002244] text-white shadow-soft"
            >
              <Navigation className="w-4 h-4 mr-2" />
              Optimizar Rutas
            </Button>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto p-4 lg:p-6 space-y-6">
        {/* Banner de Inspecciones Autoalimentadas */}
        <Card className="bg-gradient-to-br from-purple-50 to-indigo-50 dark:from-purple-900/20 dark:to-indigo-900/20 border-purple-200 dark:border-purple-800">
          <div className="p-5">
            <div className="flex items-start gap-4">
              <div className="flex items-center justify-center w-12 h-12 rounded-xl bg-gradient-to-br from-purple-600 to-indigo-600 shadow-lg flex-shrink-0">
                <RefreshCw className="w-6 h-6 text-white" />
              </div>
              <div className="flex-1">
                <h3 className="text-slate-900 dark:text-white font-semibold mb-1 flex items-center gap-2">
                  🔄 Sistema de Inspecciones Autoalimentadas
                  <Badge className="bg-purple-600/20 text-purple-700 dark:text-purple-300 border-0 text-xs">
                    ACTIVO
                  </Badge>
                </h3>
                <p className="text-sm text-slate-600 dark:text-zinc-400 mb-3">
                  El calendario se autoalimenta automáticamente. Cuando completas una inspección con periodicidad definida (mensual, trimestral, semestral, anual), 
                  el sistema calcula la próxima fecha de vencimiento y la agrega al calendario automáticamente.
                </p>
                <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                  <div className="bg-white dark:bg-zinc-800 rounded-lg p-3 border border-purple-200 dark:border-purple-800">
                    <div className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                      {calendarEvents.filter(e => e.frequency === 'mensual').length}
                    </div>
                    <div className="text-xs text-slate-600 dark:text-zinc-400">Mensuales</div>
                  </div>
                  <div className="bg-white dark:bg-zinc-800 rounded-lg p-3 border border-purple-200 dark:border-purple-800">
                    <div className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                      {calendarEvents.filter(e => e.frequency === 'trimestral').length}
                    </div>
                    <div className="text-xs text-slate-600 dark:text-zinc-400">Trimestrales</div>
                  </div>
                  <div className="bg-white dark:bg-zinc-800 rounded-lg p-3 border border-purple-200 dark:border-purple-800">
                    <div className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                      {calendarEvents.filter(e => e.frequency === 'semestral').length}
                    </div>
                    <div className="text-xs text-slate-600 dark:text-zinc-400">Semestrales</div>
                  </div>
                  <div className="bg-white dark:bg-zinc-800 rounded-lg p-3 border border-purple-200 dark:border-purple-800">
                    <div className="text-2xl font-bold text-purple-600 dark:text-purple-400">
                      {calendarEvents.filter(e => e.frequency === 'anual').length}
                    </div>
                    <div className="text-xs text-slate-600 dark:text-zinc-400">Anuales</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Card>

        {/* Sugerencias Inteligentes */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
          {smartSuggestions.map((suggestion) => (
            <Card 
              key={suggestion.id}
              className={`border-l-4 ${
                suggestion.type === 'legal' ? 'border-l-[#D32F2F]' : 
                suggestion.type === 'route' ? 'border-l-[#003366]' : 
                'border-l-green-500'
              } bg-white dark:bg-zinc-800`}
            >
              <div className="p-4">
                <div className="flex items-start gap-3 mb-3">
                  <div className={`p-2 rounded-lg ${
                    suggestion.type === 'legal' ? 'bg-red-500/20' : 
                    suggestion.type === 'route' ? 'bg-blue-900/20' : 
                    'bg-green-500/20'
                  }`}>
                    {suggestion.type === 'legal' && <AlertTriangle className="w-5 h-5 text-[#D32F2F]" />}
                    {suggestion.type === 'route' && <Navigation className="w-5 h-5 text-[#003366]" />}
                    {suggestion.type === 'productivity' && <Clock className="w-5 h-5 text-green-600" />}
                  </div>
                  <div className="flex-1">
                    <p className="text-slate-900 dark:text-white text-sm font-medium mb-1">
                      {suggestion.suggestion}
                    </p>
                    <p className="text-xs text-green-600 dark:text-green-400">
                      💡 {suggestion.savings}
                    </p>
                  </div>
                </div>
                <Button 
                  size="sm" 
                  variant="outline"
                  className="w-full border-slate-200 dark:border-zinc-600 text-[#003366] dark:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-900/20"
                >
                  {suggestion.actionLabel}
                </Button>
              </div>
            </Card>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Calendario */}
          <div className="lg:col-span-2">
            <Card className="bg-white dark:bg-zinc-800 border-slate-200 dark:border-zinc-700">
              <div className="p-5">
                <div className="flex items-center justify-between mb-6">
                  <h2 className="text-xl text-slate-900 dark:text-white font-semibold">
                    {monthNames[currentMonth.getMonth()]} {currentMonth.getFullYear()}
                  </h2>
                  <div className="flex gap-2">
                    <Badge className="bg-[#D32F2F]/20 text-[#D32F2F] border-0">
                      <AlertTriangle className="w-3 h-3 mr-1" />
                      Vencimiento Legal
                    </Badge>
                  </div>
                </div>

                {/* Grid del calendario */}
                <div className="grid grid-cols-7 gap-2 mb-2">
                  {daysOfWeek.map((day) => (
                    <div key={day} className="text-center text-xs font-medium text-slate-600 dark:text-zinc-400 py-2">
                      {day}
                    </div>
                  ))}
                </div>

                <div className="grid grid-cols-7 gap-2">
                  {getDaysInMonth().map((dayData, index) => {
                    if (!dayData) {
                      return <div key={`empty-${index}`} className="aspect-square" />;
                    }

                    const isSelected = dayData.dateStr === selectedDate;
                    const isToday = dayData.dateStr === '2026-01-27';

                    return (
                      <button
                        key={dayData.dateStr}
                        onClick={() => setSelectedDate(dayData.dateStr)}
                        className={`aspect-square rounded-lg p-2 text-sm transition-all relative interactive ${
                          isSelected
                            ? 'bg-[#003366] text-white shadow-soft-lg'
                            : isToday
                            ? 'bg-blue-50 dark:bg-blue-900/20 text-[#003366] dark:text-blue-400 ring-2 ring-[#003366] dark:ring-blue-600'
                            : dayData.events.length > 0
                            ? 'bg-slate-100 dark:bg-zinc-700 hover:bg-slate-200 dark:hover:bg-zinc-600'
                            : 'hover:bg-slate-100 dark:hover:bg-zinc-700'
                        }`}
                      >
                        <div className={`font-medium ${isSelected ? 'text-white' : 'text-slate-900 dark:text-white'}`}>
                          {dayData.day}
                        </div>
                        {dayData.events.length > 0 && (
                          <div className="flex justify-center gap-1 mt-1">
                            {dayData.hasCritical && (
                              <div className="w-1.5 h-1.5 rounded-full bg-[#D32F2F]" />
                            )}
                            {dayData.hasLegal && !dayData.hasCritical && (
                              <div className="w-1.5 h-1.5 rounded-full bg-amber-500" />
                            )}
                            {!dayData.hasLegal && !dayData.hasCritical && (
                              <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
                            )}
                          </div>
                        )}
                      </button>
                    );
                  })}
                </div>
              </div>
            </Card>
          </div>

          {/* Eventos del día seleccionado */}
          <div className="space-y-4">
            <Card className="bg-white dark:bg-zinc-800 border-slate-200 dark:border-zinc-700">
              <div className="p-5">
                <h3 className="text-slate-900 dark:text-white font-semibold mb-4">
                  Eventos del {new Date(selectedDate).getDate()} de {monthNames[new Date(selectedDate).getMonth()]}
                </h3>
                
                {isLoadingEvents ? (
                  <div className="text-center py-8 text-slate-400 flex flex-col items-center gap-2">
                    <RefreshCw className="w-6 h-6 animate-spin" />
                    Cargando eventos...
                  </div>
                ) : selectedEvents.length === 0 ? (
                  <div className="text-center py-8">
                    <Calendar className="w-12 h-12 text-slate-300 dark:text-zinc-600 mx-auto mb-3" />
                    <p className="text-slate-600 dark:text-zinc-400 text-sm mb-4">
                      No hay eventos programados
                    </p>
                    <Button
                      onClick={() => setShowEventForm(true)}
                      className="bg-blue-600 hover:bg-blue-700 text-white"
                    >
                      <Plus className="w-4 h-4 mr-2" />
                      Agregar Actividad
                    </Button>
                  </div>
                ) : (
                  <div className="space-y-3">
                    {selectedEvents.map((event: any) => (
                      <div
                        key={event.id}
                        className={`p-4 rounded-lg border-2 transition-all interactive ${
                          event.priority === 'critical'
                            ? 'border-[#D32F2F] bg-red-50 dark:bg-red-900/20'
                            : event.priority === 'high'
                            ? 'border-amber-500 bg-amber-50 dark:bg-amber-900/20'
                            : 'border-slate-200 dark:border-zinc-700 bg-slate-50 dark:bg-zinc-700/50'
                        }`}
                      >
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex gap-2">
                            <Badge className={`${
                              event.priority === 'critical' ? 'bg-[#D32F2F] text-white' :
                              event.priority === 'high' ? 'bg-amber-500 text-white' :
                              'bg-blue-600 text-white'
                            } border-0 text-xs`}>
                              {event.type === 'legal' ? 'LEGAL' : event.type === 'inspection' ? 'INSPECCIÓN' : 'RUTINA'}
                            </Badge>
                            {event.autoGenerated && (
                              <Badge className="bg-purple-600/20 text-purple-700 dark:text-purple-300 border-0 text-xs flex items-center gap-1">
                                <RefreshCw className="w-3 h-3" />
                                AUTO
                              </Badge>
                            )}
                          </div>
                        </div>
                        
                        <h4 className="text-slate-900 dark:text-white font-medium mb-2">
                          {event.title}
                        </h4>
                        
                        {event.autoGenerated && event.lastCompleted && (
                          <div className="mb-2 p-2 bg-purple-50 dark:bg-purple-900/20 rounded text-xs text-purple-900 dark:text-purple-200">
                            <div className="flex items-center gap-1 mb-1">
                              <RefreshCw className="w-3 h-3" />
                              <span className="font-semibold">Inspección Recurrente ({event.frequency})</span>
                            </div>
                            <p className="text-purple-700 dark:text-purple-300">
                              Última realizada: {new Date(event.lastCompleted).toLocaleDateString('es-CL')}
                            </p>
                            {event.notes && <p className="text-purple-600 dark:text-purple-400 mt-1">📝 {event.notes}</p>}
                          </div>
                        )}
                        
                        <div className="space-y-1 text-xs">
                          <div className="flex items-center gap-2 text-slate-600 dark:text-zinc-400">
                            <Clock className="w-3 h-3" />
                            {event.time}
                          </div>
                          <div className="flex items-center gap-2 text-slate-600 dark:text-zinc-400">
                            <MapPin className="w-3 h-3" />
                            {event.location}
                          </div>
                          {event.company && (
                            <div className="flex items-center gap-2 text-slate-600 dark:text-zinc-400">
                              <span className="font-semibold">Empresa:</span>
                              {event.company}
                            </div>
                          )}
                        </div>

                        {event.deadline && (
                          <div className="mt-3 pt-3 border-t border-slate-200 dark:border-zinc-600">
                            <div className="flex items-start gap-2">
                              <Bell className="w-4 h-4 text-[#D32F2F] mt-0.5 flex-shrink-0" />
                              <p className="text-xs text-[#D32F2F] dark:text-red-400 font-medium">
                                {event.deadline}
                              </p>
                            </div>
                          </div>
                        )}

                        <Button
                          size="sm"
                          onClick={() => handleMarkCompleted(event)}
                          disabled={event.status === 'completed'}
                          className="w-full mt-3 bg-[#003366] hover:bg-[#002244] text-white disabled:opacity-50"
                        >
                          <CheckCircle2 className="w-4 h-4 mr-2" />
                          {event.status === 'completed' ? 'Completado' : 'Marcar Completado'}
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </Card>
          </div>
        </div>
      </div>

      {/* Modal para crear eventos */}
      {showEventForm && (
        <GoogleCalendarEventForm
          selectedDate={selectedDate}
          onClose={() => setShowEventForm(false)}
          onSubmit={handleCreateEvent}
        />
      )}
    </div>
  );
}